language: node_js
node_js:
  - '15.10.0'
dist: trusty
os: linux
addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
deploy:
  on:
    tags: true
  provider: npm
  cleanup: false
  email: "casinhas32@hotmail.com"
  api_token: $NPMJS_DEPLOY_TOKEN
