language: node_js
node_js:
  - '16.13.0'
dist: trusty
os: linux
addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Repo for Yarn
  - npm i -g yarn
cache:
  yarn: true
deploy:
  on:
    tags: true
  provider: npm
  cleanup: false
  email: "tiago.gaspar.casinhas@gmail.com"
  api_token: $NPMJS_DEPLOY_TOKEN
